services:
  postservice_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postservice_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'

  commentservice_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: 'commentservice_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'

  reviewservice_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: 'reviewservice_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"